"""Base database creation

Revision ID: 7289f6b75b37
Revises:
Create Date: 2021-03-15 16:29:40.471847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7289f6b75b37"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_facebook_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("profile_picture_path", sa.String(length=255), nullable=False),
        sa.Column("topics", sa.Text(), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "missions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("info", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_facebook_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["data_facebook_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_facebook_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["data_facebook_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_location_point",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["data_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("sent_to", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["data_users.id"]),
        sa.ForeignKeyConstraint(["sent_to"], ["data_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_messages")
    op.drop_table("data_location_point")
    op.drop_table("data_facebook_posts")
    op.drop_table("data_facebook_comments")
    op.drop_table("missions")
    op.drop_table("data_users")
    op.drop_table("data_facebook_users")
    # ### end Alembic commands ###
